### ISSUE TITLE
Use YAML maps instead of sequences for arrays.

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#17]
I specified that arrays should be represented by maps not by sequences so that it is possible to just modify an element in the middle of the array.

The example YAML from the README.md should look like this:

```YAML
  manager_config: 
    device_configs: 
    0:
      trigger : 
        0:
          falling : false 
          rising : true 
      trigger_threshold : 
        0: 0.3499 
        1: 0.35 
        2: 0.36666 
      gating_block :
      0:  
        mode : 1 
        negate : true 
      auto_trigger_period : 20 
    1: 
      trigger : 
        0: 
          falling : true 
          rising : false 
      channel : 
        0:
          enable : true
          rising : false 
  grouping : 
    enabled : true 
```

**Comment by Bassem-Ramzy** [comment]
@sulimma 
Just to make sure
```YAML
      trigger : 
        falling : false 
        rising : true 
```
Means we apply those values on the first trigger (first array element) in the configuration, i.e. this is equivalent to:
```YAML
      trigger : 
       0:
         falling : false 
         rising : true 
```
right?

**Comment by Bassem-Ramzy** [comment]
> @sulimma
> Just to make sure
> 
> ```yaml
>       trigger : 
>         falling : false 
>         rising : true 
> ```
> 
> Means we apply those values on the first trigger (first array element) in the configuration, i.e. this is equivalent to:
> 
> ```yaml
>       trigger : 
>        0:
>          falling : false 
>          rising : true 
> ```
> 
> right?

And if so, shall this be applied also on the "device_configs"?

**Comment by sulimma** [comment]
No. This was my mistake when manually rewriting the yaml. 
I don't think we should support two different formats. If trigger is an array it shall be configured as such. The only topic I wanted to open here is the issue sequences vs. maps. 
So: 
```YAML
trigger:
  2:
    falling: false
    rising: true
```
results in the values applied to entry 2.
```YAML
trigger:
  -1:
    falling: false
    rising: true
```
Results in the values applied to all entries
